version: '3'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
      - ./templates:/templates
    environment:
      #- DOCKER_JUPYTER_CONTAINER=jupyter/scipy-notebook
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=jupyterhub
      - GITLAB_HOST=http://gitlab.mmcs.sfedu.ru
      - OAUTH_CALLBACK_URL=https://opsgroup.ru/hub/oauth_callback
      - OAUTH_CLIENT_ID=aced8f0ac4322286ac6948d3fccf237c479424b5ad0e6dfb393e372caf0c97be
      - OAUTH_CLIENT_SECRET=61abc2923708babeee1dd8779da07c89447129978346bc9362be78d2334908db
      - HOST
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
    restart: on-failure

  jupyterlab:
    build: jupyterlab
    image: jupyter/scipy-notebook
    container_name: jupyterlab-throaway
    network_mode: none
    command: echo

  reverse-proxy:
    image: traefik:v1.7.18
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      - /etc/certs:/etc/certs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

volumes:
  jupyterhub_data:
