version: '3'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyter/scipy-notebook
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=jupyterhub
      - GITLAB_HOST=http://gitlab.mmcs.sfedu.ru
      - OAUTH_CALLBACK_URL=https://grade-dev.mmcs.sfedu.ru/hub/oauth_callback
      - OAUTH_CLIENT_ID=b27b5560b403e75e92fb80f44cc4a458e3bd455cbe3cbe4bba3fb08c48e76a10
      - OAUTH_CLIENT_SECRET=197727cd4b08fd3278ba0990d59fb60eb1dacb5b73f564cfab21692f0a65ac81
      - HOST
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
    restart: on-failure

  jupyterlab:
    build: jupyterlab
    image: jupyter/scipy-notebook
    container_name: jupyterlab-throaway
    network_mode: none
    command: echo

  reverse-proxy:
    image: traefik
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      - /etc/certs:/etc/certs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

volumes:
  jupyterhub_data:
